### ISSUE TITLE
Add support for runtime 21.08

### ISSUE THREAD

**Issue by Unrud** [flathub/org.freedesktop.Sdk.Extension.mono6#4]
Required by https://github.com/flathub/net.openra.OpenRA/pull/17

**Comment by darkdragon-001** [comment]
Fixed in #5

**Comment by darkdragon-001** [comment]
@Unrud Can you please test https://flathub.org/builds/#/builders/32/builds/59869 once it finished building?
If it works, I will publish it directly.
