### ISSUE TITLE
Please include mono's msbuild (either in this SDK or as separate flatpak package)

### ISSUE THREAD

**Issue by geekley** [flathub/org.freedesktop.Sdk.Extension.mono6#6]
When using snap VSCode/ium I was able to use C# / msbuild with just mono, not requiring dotnet installation.
All I had to do was to install mono's msbuild with `sudo apt install msbuild` as per this OmniSharp message:
```
[warn]: OmniSharp.MSBuild.Discovery.Providers.MonoInstanceProvider
        It looks like you have Mono 6.4.0 or greater installed but MSBuild could not be found.
Try installing MSBuild into Mono (e.g. 'sudo apt-get install msbuild') to enable better MSBuild support, or [...]
```

However, when migrating to flatpak version of VSCode/ium, it seems `msbuild` isn't available in flatpak mono.
Though I can access the command from `/run/host/...` I can't get it to work with the C# extension. I tried many things, but it didn't work.

Ideally mono's `msbuild` (from apt install when adding [mono-project](https://www.mono-project.com/download/stable/#download-lin-ubuntu) as a source) should be either included in this SDK package; or in something like a `org.freedesktop.Sdk.Extension.mono6.msbuild` or similar, so we can just install it as a flatpak SDK.

I'd like to emphasize again that I DON'T want to use `dotnet`.
This used to work in non-flatpak VSCode/ium, and it should work in flatpaked Code as well when adding a proper SDK.

**Comment by geekley** [comment]
I managed to get it working for my use case by copying some files from my msbuild in mono to their flatpak equivalent paths.
I did something similar to this:
`./msbuild-deb-to-flatpak.sh`
```bash
#!/usr/bin/env bash
FLATPAK_MSBUILD_DIR=/var/lib/flatpak/runtime/org.freedesktop.Sdk.Extension.mono6/x86_64/21.08/active/files
DEB_MSBUILD_DIR=/usr/lib/mono

sudo cp -vrut $FLATPAK_MSBUILD_DIR/bin/ ./msbuild

sudo cp -vrut $FLATPAK_MSBUILD_DIR/lib/mono/xbuild/Current/ $DEB_MSBUILD_DIR/xbuild/Current/*.props $DEB_MSBUILD_DIR/xbuild/Current/SolutionFile/

sudo cp -vrut $FLATPAK_MSBUILD_DIR/lib/mono/msbuild/Current/bin/ $DEB_MSBUILD_DIR/msbuild/Current/bin/*
sudo ln -s Current $FLATPAK_MSBUILD_DIR/lib/mono/msbuild/15.0
```
Modified `./msbuild` to copy:
```sh
#!/bin/sh
MONO_GC_PARAMS="nursery-size=64m,$MONO_GC_PARAMS" exec /usr/lib/sdk/mono6/bin/mono --assembly-loader=strict $MONO_OPTIONS /usr/lib/sdk/mono6/lib/mono/msbuild/Current/bin/MSBuild.dll "$@"
```
This is just an example (I didn't check if all necessary files were copied, but it worked on a simple test).

---
So to get this working, the flatpak would probably need to have mono+msbuild together (since the files likely need to be "merged" inside the same `/usr/lib/sdk/xxxxx/` path). So if a separate package is preferred, it would likely need to include mono anyway.

The downloaded package would be from something like:
`https://download.mono-project.com/sources/msbuild/msbuild-16.6+xamarinxplat.2021.01.15.16.11.tar.xz`
Of course, it would have to be compatible with the corresponding mono package.

**Comment by Kirbyrawr** [comment]
Any more info related to this issue? Can MSBuild be included to make it the full distribution of Mono?
Is very important to have it in order to use Visual Studio Code with Omnisharp when working with Unity projects in an inmutable distro.

**Comment by darkdragon-001** [comment]
Just yesterday, dotnet/msbuild#4196 was closed as _not planned_. There are some forks in the mono org though: [msbuild](https://github.com/mono/msbuild) and [linux-packaging-msbuild](https://github.com/mono/linux-packaging-msbuild)

**Comment by Kirbyrawr** [comment]
Yeah, i was talking more about the mono fork because that seems enough to make it work.
Do you think it's viable?

Thanks for the reply.

**Comment by darkdragon-001** [comment]
As I am not using mono myself any more (just needed it to build Pinta before their move to [dotnet6](https://github.com/flathub/org.freedesktop.Sdk.Extension.dotnet6)), I won't spend time on adding it myself but I also don't see a reason to not include it. So feel free to create a PR and test it and I would be happy to accept and merge.

**Comment by Kirbyrawr** [comment]
> As I am not using mono myself any more (just needed it to build Pinta before their move to [dotnet6](https://github.com/flathub/org.freedesktop.Sdk.Extension.dotnet6)), I won't spend time on adding it myself but I also don't see a reason to not include it. So feel free to create a PR and test it and I would be happy to accept and merge.

That makes sense, appreciate. I may take a look into it!

**Comment by FullStackFlamingo** [comment]
Thanks @priahoud for those msbuild PRs! This will finally re-enable Unity development! It looks like it will be a few years at least before Unity moves away from mono/msbuild.
